<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

//add_action( 'genesis_sidebar', 'genesis_do_sidebar' );



//* Force full width content layout
add_filter( 'genesis_site_layout', '__genesis_return_content_sidebar' );

add_filter( 'body_class', 'wpsites_blog_page_body_class' );
function wpsites_blog_page_body_class( $classes ) {
    $classes[] = 'single-blog-post';
    return $classes;
}

//add_action('genesis_loop', 'genesis_standard_loop', 5);

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
genesis();
